OmniscienceBotCore/OmniscienceBotCore/Controllers/SharedController.cs
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using OmniscienceBotCore.Channel;

namespace OmniscienceBotCore.Controllers
{
    public class SharedController : Controller
    {
        TwitchChannels TwitchChannels;
        public SharedController(TwitchChannels twitchChannels)
        {
            TwitchChannels = twitchChannels;
        }

        public PartialViewResult Login()
        {
            string channel = User.Claims.FirstOrDefault(c => c.Type == ClaimsIdentity.DefaultNameClaimType)?.Value;
            if (channel == null) channel = "";
            return PartialView(channel);
        }
    }

    public class _SongRequestController : Controller
    {
        TwitchChannels TwitchChannels;
        public _SongRequestController(TwitchChannels twitchChannels)
        {
            TwitchChannels = twitchChannels;
        }

        public string CheckForSong()
        {
            //https://www.mikesdotnetting.com/article/325/partials-and-ajax-in-razor-pages
            //http://www.binaryintellect.net/articles/65cfe9cd-b98f-48b7-825d-31ae8008a91a.aspx
            string channel = User.Claims.FirstOrDefault(c => c.Type == ClaimsIdentity.DefaultNameClaimType)?.Value;
            if (channel != null) return TwitchChannels[channel].SongRequestCheck?.ID;
            else return "";
        }
    }

    public class _AjaxSoundCommandController : Controller
    {
        TwitchChannels TwitchChannels;
        public _AjaxSoundCommandController(TwitchChannels twitchChannels)
        {
            TwitchChannels = twitchChannels;
        }

        public string IsThereAnything()
        {
            string channel = User.Claims.FirstOrDefault(c => c.Type == ClaimsIdentity.DefaultNameClaimType)?.Value;
            if (channel != null && TwitchChannels.Channels.ContainsKey(channel)) return TwitchChannels[channel].QueueIsEmpty ? "" : "+";
            else return "";
        }

        public PartialViewResult CallAjax()
        {
            string channel = User.Claims.FirstOrDefault(c => c.Type == ClaimsIdentity.DefaultNameClaimType)?.Value;
            if (channel != null)
            {
                string path = TwitchChannels[channel].CheckForQueue;

                if (path != "") return new PartialViewResult() { ViewName = "_AjaxSoundCommand", ViewData = new Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<string>(ViewData, path) };
                else return null;
            }
            else return null;
        }
    }
}

OmniscienceBotCore/OmniscienceBotCore/Controllers/SpotifyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using OmniscienceBotCore.Channel;
using OmniscienceBotCore.Services;
using SpotifyAPI.Web;
using static OmniscienceBotCore.Startup;

namespace OmniscienceBotCore.Controllers
{
    [Authorize(Roles = "Admin, Streamer")]
    public class SpotifyController : Controller
    {

        private readonly ILogger<HomeController> _logger;
        TwitchClientWrapper TwitchClientWrapper;
        readonly IOptions<AppConfig> config;
        TwitchChannels TwitchChannels;

        public SpotifyController(TwitchChannels twitchChannels, ILogger<HomeController> logger, TwitchClientWrapper twitchClientWrapper, IOptions<AppConfig> config)
        {
            TwitchChannels = twitchChannels;
            _logger = logger;
            TwitchClientWrapper = twitchClientWrapper;
            this.config = config;
        }
        public IActionResult Index()
        {
            string channel = User.Claims.FirstOrDefault(c => c.Type == ClaimsIdentity.DefaultNameClaimType)?.Value;
            if (channel != null) return View();
            else return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Login(string code = "")
        {
            string channel = User.Claims.FirstOrDefault(c => c.Type == ClaimsIdentity.DefaultNameClaimType)?.Value;
            if (channel == null) RedirectToAction("Index");

            string clientID = "0771b503300e49d398bec27b62c4b524";
            string clientSecret = "fbe8ace792754b138cfc8e934fe44b30";

            string redirect_uri = $"{config.Value.ReleaseRedirectUri}/Spotify/Login";

#if DEBUG
            redirect_uri = $"{config.Value.DebugRedirectUri}/Spotify/Login";
#endif

            if (code != "")
            {
                var response = await new OAuthClient().RequestToken(new AuthorizationCodeTokenRequest(clientID, clientSecret, code, new Uri(redirect_uri)));

                TwitchChannels[channel].SpotifyInit(response.RefreshToken, response.AccessToken);
            }
            else
            {

                var loginRequest = new LoginRequest(
                    new Uri(redirect_uri),
                    clientID,
                    LoginRequest.ResponseType.Code)
                {
                    Scope = new[]
                    {
                        Scopes.UserReadCurrentlyPlaying,
                        Scopes.UserReadPlaybackState,
                        Scopes.UserModifyPlaybackState
                    }
                };

                return Redirect(loginRequest.ToUri().ToString());
            }
            return RedirectToAction("Index");
        }
    }
}

OmniscienceBotCore/OmniscienceBotCore/Views/Shared/Login.cshtml
@*@model string*@

@*@if (Model != null && Model != "")*@
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="ChannelSettings" asp-action="Index">Settings</a>
    </li>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

OmniscienceBotCore/OmniscienceBotCore/Views/Shared/_AjaxSoundCommand.cshtml
@model string
@*https://www.w3schools.com/tags/ref_av_dom.asp*@
<audio id='cmdAudio' controls controlsList="nodownload" autoplay preload='auto' style="height: 30%; vertical-align: sub">
    <source src='~/Data/Sounds/@Model' type='audio/wav'>
</audio>

OmniscienceBotCore/OmniscienceBotCore/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
@using Microsoft.AspNetCore.Http


<!DOCTYPE html>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.js"></script>
<script>
    function fetchdata() {
        $.ajax({
            url: '/_AjaxSoundCommand/IsThereAnything',
            type: 'get',
            dataType: 'text',
            complete: function (response) {
                console.log(response);
                if (response.responseText == '+' && (document.getElementById("cmdAudio") == null || document.getElementById("cmdAudio").ended)) {
                    $("#ajaxTarget").load("/_AjaxSoundCommand/CallAjax");
                }
            }
        });
    }

    //https://www.codeproject.com/Questions/1117942/Play-audio-and-video-file-using-MVC
    //https://forums.asp.net/t/2127539.aspx?How+can+I+play+a+wave+file+in+mvc

</script>

@if (User.IsInRole("Admin") || User.IsInRole("Authorized"))
{
    @*<script>
        $(function () {
            setInterval(fetchdata, 5000);
        });
    </script>*@
}

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>OmniBot</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-dark.css" />
    <meta name="color-scheme" content="light dark">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-dark.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OmniBot</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @{
                            if ((User.IsInRole("Admin") || User.IsInRole("Streamer") || User.IsInRole("Moderator")))
                            {
                                if (!User.IsInRole("Moderator") ||
                                (User.IsInRole("Moderator") &&
                                User.Claims.FirstOrDefault(c => c.Type == "Scopes").Value.Contains("Events")))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                                    </li>
                                }
                                if (!User.IsInRole("Moderator") ||
                                (User.IsInRole("Moderator") &&
                                User.Claims.FirstOrDefault(c => c.Type == "Scopes").Value.Contains("Commands")))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Commands" asp-action="Index">Commands</a>
                                    </li>
                                }
                                if (!User.IsInRole("Moderator") ||
                                (User.IsInRole("Moderator") &&
                                User.Claims.FirstOrDefault(c => c.Type == "Scopes").Value.Contains("Pastes")))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Pastes" asp-action="Index">Pastes</a>
                                    </li>
                                }
                                if (!User.IsInRole("Moderator") ||
                                (User.IsInRole("Moderator") &&
                                User.Claims.FirstOrDefault(c => c.Type == "Scopes").Value.Contains("Counters")))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Counters" asp-action="Index">Counters</a>
                                    </li>
                                }
                                if (!User.IsInRole("Moderator") ||
                                (User.IsInRole("Moderator") &&
                                User.Claims.FirstOrDefault(c => c.Type == "Scopes").Value.Contains("StreamAnnouncements")))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="StreamAnnouncements" asp-action="Index">Announcements</a>
                                    </li>
                                }
                                if (!User.IsInRole("Moderator"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Moderators" asp-action="Index">Moderators</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Interactions" asp-action="Index">Interactions</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Spotify" asp-action="Index">Spotify</a>
                                    </li>
                                }
                            }
                        }
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row">
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            if (User.Identity.IsAuthenticated && (!User.IsInRole("Unauthorized") || !User.IsInRole("Guest")))
                            {
                                if (User.IsInRole("Admin") || User.IsInRole("Moderator"))
                                {
                                    <li class="nav-item">
                                        <div class="nav-link text-light">Currently on: @User.Identity.Name</div>
                                    </li>
                                }
                                if (User.IsInRole("Admin"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="AdminPanel" asp-action="Index">AdminPanel</a>
                                    </li>
                                }

                                if (!User.IsInRole("Moderator"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Moderation" asp-action="Index">Moderation</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="ChannelSettings" asp-action="Index">Settings</a>
                                    </li>
                                }
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Login">Log in</a>
                                </li>
                            }
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
        <div class="container">
            @*<partial name="_SongRequest"/>*@
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>

OmniscienceBotCore/OmniscienceBotCore/Views/Shared/_SongRequest.cshtml
@*<!DOCTYPE html>
    <html>
    <head>
        <meta charset='UTF-8' />
        <style type='text/css'>

            .videoWrapper {
            }

                .videoWrapper iframe {
                    position: absolute;
                    top: 0;
                    left: 0;
                    width: 100%;
                    height: 100%;
                }
        </style>
    </head>
    <body>*@
<div id="player"></div>

<script>
    var player;
    function fetchsongdata() {
        if (nextID == '')
            $.ajax({
                url: '/_SongRequest/CheckForSong',
                type: 'get',
                dataType: 'text',
                complete: function (response) {
                    if (response.responseText != '')
                        if (currentID == '') {
                            currentID = response.responseText;
                            player.setVideoId(currentID);
                        }
                        else nextID = response.responseText;
                }
            });
    }


    //https://www.codeproject.com/Questions/1117942/Play-audio-and-video-file-using-MVC
    //https://forums.asp.net/t/2127539.aspx?How+can+I+play+a+wave+file+in+mvc

    // 2. This code loads the IFrame Player API code asynchronously.
    var tag = document.createElement('script');

    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    // 3. This function creates an <iframe> (and YouTube player)
    //    after the API code downloads.
    var autoPlay = true;
    var quality = "default";
    var currentID = 'E7JzX4CHJYg';
    var nextID = '';

    function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
            height: '400',
            width: '400',
            videoId: currentID,
            //suggestedQuality: "hd720",
            events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange,
                'onPlaybackQualityChange': onPlayerPlaybackQualityChange
            }
        });
    }

    function onPlayerReady(event) {
        //player.playVideo();
        setInterval(fetchsongdata, 5000);
    }

    function onPlayerStateChange(event) {
        console.log(event.data);
        if (event.data == YT.PlayerState.ENDED) {
            if (nextID == '')
                currentID = '';
            else {
                currentID = nextID;
                nextID = '';
                setVideoId(currentID);
                //player.playVideo();
            }
        }
    }

    function onPlayerPlaybackQualityChange(event) {
    }

    function setPlayerState(state) {
        if (state == "ended") player.stopVideo();
        else if (state == "start") player.playVideo();
        else if (state == "pause") player.pauseVideo();
    }

    function setVolume(volume) {
        player.setVolume(volume);
    }

    function setVideoId(videoId) {
        if (autoPlay) player.loadVideoById(videoId, 0, quality);
        else player.cueVideoById(videoId, 0, quality);
    }

    function setQuality(quality) {
        player.setPlaybackQuality(quality);
    }
</script>
@*</body>
    </html>*@